// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	  int repeticiones = Integer.parseInt(args[0]);
	  double lessThan = 0;
	  double moreThan = 0;
	  int i = 0;
	  double number = 0;
	  
	  while(i < repeticiones){
	  	number = Math.random();
		if (number > 0.5){
			moreThan++;
			i++;
		}
		else{
			lessThan++;
			i++;
		}
		
		
	}
	System.out.println("> 0.5: " + (int)moreThan + " times");
	System.out.println("<= 0.5: " + (int)lessThan + " times");
	if(moreThan > 0 && lessThan > 0){
	double ratio = Math.min(moreThan,lessThan) / Math.max(moreThan,lessThan);
	System.out.println("Ratio: " + ratio);
	}


	
	
}
}
